### ISSUE TITLE
KDD 2024 -- August 24-29, Barcelona, Spain

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/talks#15]
https://kdd2024.kdd.org/

potential themes:

- Ibis (adapt one of the existing tutorials)
- IbisML

**Comment by ncclementi** [comment]
CFP for papers deadline : 02/01/2024: Do we want to submit a paper?  Given the guidelines, I think we are a bit late for this one. 

### CFP Deadline for Hands on Tutorial is Friday, March 29th, 2024.

By looking at what they request for the proposal, we should be able to adapt the submission to PyCon, and maybe include some extra topic because it's for a 3h long tutorial.  Given the titles of past tutorials ([2023](https://kdd.org/kdd2023/tutorials/), [2022](https://kdd.org/kdd2022/handsOnTutorial.html)), we might have to re-think the title, and we will have to put work on points 8-11.  

**Proposal**: https://kdd2024.kdd.org/call-for-hands-on-tutorials/

We invite proposals from researchers, creators, experienced practitioners and tutors of data mining systems and tools. Each proposal must include the following details:

1. A descriptive title
2. Abstract (300 words)
3. Target audience and prerequisites for the tutorial (e.g. audience expertise)
4. Tutors (name, affiliation, email, address, phone)
5. Tutors’ short bio and expertise related to the tutorial (up to 200 words per tutor)
              1. List of in-person presenters, i.e., tutors who will attend KDD and present part of the tutorial
              2. List of contributors, i.e., tutors who will only help prepare the tutorial material
6. Corresponding tutor with her/his email address
7. Tutorial outline. Please provide as much detail as possible.
8. If the tutorial or a similar/highly related tutorial has been presented before (either by the same author(s) or by others): A list of forums, their event dates and locations, the number of participants, and the similarities/differences of prior tutorials to the one proposed for prior KDDs (up to 100 words for each entry)
9. A list of up to 30 most important references that will be covered in the tutorial
10. Strategies that you plan to employ to encourage audience participation and interactivity throughout the tutorial presentation
11. A brief discussion of the potential societal impacts of your tutorial

**Comment by cpcloud** [comment]
@ianmcook I believe you suggested this one.

What's the priority on doing a tutorial here? (Papers out because we missed that deadline). 

We've got other things in flight (PyCon * 2, Data Council) and scipy (I think we're submitting 3 talks and a tutorial), so just trying to understand whether we should prioritize this or not.

**Comment by ianmcook** [comment]
@cpcloud I think KDD should be a priority for us because it's an opportunity to get outside the usual Python comfort zone / echo chamber and expose a different audience to Ibis and to the composable data ecosystem story. From what I have heard, KDD is a good place to encounter influential people thinking across domains.

**Comment by cpcloud** [comment]
@ianmcook Thanks!

Is there a particular angle that would be most effective in your opinion, or would one of our existing talks work?

**Comment by ianmcook** [comment]
I'm not deeply familiar with the existing tutorial that y'all have given previously, but my guess is that 90+% of it could stay the same, with 10% new content consisting of:
- a small unit on Ibis ML
- a small unit on Ibis for streaming
- some lecture content on the big-picture composable data ecosystem stuff

**Comment by cpcloud** [comment]
https://kdd2024.kdd.org/call-for-hands-on-tutorials/

http://cmt3.research.microsoft.com/KDDTutorials2023/ is the place to submit
